protected/models/Religion.php
<?php

/**
 * This is the model class for table "religion".
 *
 * The followings are the available columns in table 'religion':
 * @property integer $religion_id
 * @property string $religion_name
 * @property integer $religion_organization_id
 * @property integer $religion_created_by
 * @property string $religion_created_date
 */
class Religion extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Religion the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'religion';
	}
	public function defaultScope() 
	{
       		return array(
           		'order' => 'religion_name'
	        );
  	}
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('religion_name, religion_organization_id, religion_created_by, religion_created_date', 'required','message'=>''),
			array('religion_organization_id, religion_created_by', 'numerical', 'integerOnly'=>true),
			array('religion_name', 'length', 'max'=>30),
			array('religion_name', 'unique','message'=>'Already Exists.'),
			array('religion_name','CRegularExpressionValidator','pattern'=>'/^([A-Za-z  ]+)$/','message'=>''),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('religion_id, religion_name, religion_organization_id, religion_created_by, religion_created_date', 'safe', 'on'=>'search'),
			
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		'Rel_org' => array(self::BELONGS_TO, 'Organization','religion_organization_id'),
		'Rel_user' => array(self::BELONGS_TO, 'User','religion_created_by'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'religion_id' => 'Religion',
			'religion_name' => 'Religion',
			'religion_organization_id' => 'Organization',
			'religion_created_by' => 'Created By',
			'religion_created_date' => 'Creation Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('religion_id',$this->religion_id);
		$criteria->compare('religion_name',$this->religion_name,true);
		$criteria->compare('religion_organization_id',$this->religion_organization_id);
		$criteria->compare('religion_created_by',$this->religion_created_by);
		$criteria->compare('religion_created_date',$this->religion_created_date,true);

		$religion_data =  new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
		$_SESSION['religion_data']=$religion_data;
		return $religion_data;
	}
	private static $_items=array();

        public static function items()
        {
            if(isset(self::$_items))
                self::loadItems();
            return self::$_items;
        }

    public static function item($code)
    {
        if(!isset(self::$_items))
            self::loadItems();
        return isset(self::$_items[$code]) ? self::$_items[$code] : false;
    }

    private static function loadItems()
    {
        self::$_items=array();
        $models=self::model()->findAll();
        foreach($models as $model)
            self::$_items[$model->religion_id]=$model->religion_name;
    }
}

protected/controllers/ReligionController.php
<?php

class ReligionController extends RController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
		);
	}
	 

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */


	public function actionCreate()
	{
		$model=new Religion;

		// Uncomment the following line if AJAX validation is needed
		 $this->performAjaxValidation($model);

		if(isset($_POST['Religion']))
		{
			$model->attributes=$_POST['Religion'];
			$model->religion_organization_id = Yii::app()->user->getState('org_id');
			$model->religion_created_by=Yii::app()->user->id;
			$model->religion_created_date=new CDbExpression('NOW()');
			if($model->save())
				//$this->redirect(array('view','id'=>$model->religion_id));
				$this->redirect(array('admin'));		
}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		 $this->performAjaxValidation($model);

		if(isset($_POST['Religion']))
		{
			$model->attributes=$_POST['Religion'];
			if($model->save())
				$this->redirect(array('admin'));//$this->redirect(array('view','id'=>$model->religion_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*
		$dataProvider=new CActiveDataProvider('Religion');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
		*/
		$model=new Religion('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Religion']))
			$model->attributes=$_GET['Religion'];

		$this->render('admin',array(
			'model'=>$model,
		));

	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Religion('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Religion']))
			$model->attributes=$_GET['Religion'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Religion::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='religion-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	
	 
}

protected/views/religion/ReligionExportPdf.php
<style>
table, th, td {
  vertical-align: middle;
}
th, td, caption {
  padding: 4px 0 10px;
  text-align: center;
}

</style>
<?php 

if ($model != null):
$k=0;
?>
<table border="1">

	<tr>
		<th>
		    SN		
		</th>
 		<th>
		     Religion		
		</th>
		
 		<th>
		     Created By		
		</th>
		
 	</tr>
	<?php 
	foreach($model as $m=>$v) {
          if($m <> 0) {
            ?>	<tr>
		<td>
		      <?php echo ++$k; ?>	
		</td>
		<td>
		     <?php echo $v['religion_name']; ?>		
		</td>
		
		<td>
		     <?php echo User::model()->findByPk($v['religion_created_by'])->user_organization_email_id; ?>		
		</td>
		
 	   </tr> 
       <?php
    
       }// end if
     }// end for loop
	
?>
</table>
<?php endif; ?>

protected/views/religion/_form.php
<div class = "test" style="display:none;">
<?php        
       
if($model->scenario == 'insert')
$name = "Add Religion";
else
$name = "Edit Religion";
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
	'id'=>'mydialog',
	// additional javascript options for the dialog plugin
	'options'=>array(
		'title'=>$name,
		'autoOpen'=>true,
		'modal'=>true,	
                'height'=>'auto',
                'width'=>480,
                'resizable'=>false,
                'draggable'=>false,
		'close' => 'js:function(event, ui) { location.href = "'.Yii::app()->createUrl("religion/admin").'"; }'

	),
));
?>
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'religion-form',
	'enableAjaxValidation'=>true,
	'clientOptions'=>array('validateOnSubmit'=>true),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php //echo $form->errorSummary($model); ?>

	<div class="row1">
		<?php echo $form->labelEx($model,'religion_name'); ?>
		<?php echo $form->textField($model,'religion_name',array('size'=>25,'maxlength'=>30)); ?><span class="status">&nbsp;</span>
		<?php echo $form->error($model,'religion_name'); ?>
	</div>

	<!--<div class="row1">
		<?php echo $form->labelEx($model,'religion_organization_id'); ?>
		<?php echo $form->dropDownList($model,'religion_organization_id', Organization :: items()); ?>
		<?php echo $form->error($model,'religion_organization_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'religion_created_by'); ?>
		<?php echo $form->textField($model,'religion_created_by'); ?>
		<?php echo $form->error($model,'religion_created_by'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'religion_created_date'); ?>
		<?php echo $form->textField($model,'religion_created_date'); ?>
		<?php echo $form->error($model,'religion_created_date'); ?>
	</div>-->
<br/>
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Add' : 'Save',array('class'=>'submit')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->
<?php
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>
</div>

protected/views/religion/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<!--<div class="row">
		<?php echo $form->label($model,'religion_id'); ?>
		<?php echo $form->textField($model,'religion_id'); ?>
	</div>-->

	<div class="row">
		<?php echo $form->label($model,'religion_name'); ?>
		<?php echo $form->textField($model,'religion_name',array('size'=>30,'maxlength'=>30)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'religion_organization_id'); ?>
		<?php echo $form->textField($model,'religion_organization_id'); ?>
	</div>

	<!--<div class="row">
		<?php echo $form->label($model,'religion_created_by'); ?>
		<?php echo $form->textField($model,'religion_created_by'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'religion_created_date'); ?>
		<?php echo $form->textField($model,'religion_created_date'); ?>
	</div>-->

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/religion/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('religion_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->religion_id), array('view', 'id'=>$data->religion_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('religion_name')); ?>:</b>
	<?php echo CHtml::encode($data->religion_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('religion_organization_id')); ?>:</b>
	<?php 
		$org_name = Organization::model()->findbyPk($data->religion_organization_id);
	?>
	<?php echo CHtml::encode($org_name->organization_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('religion_created_by')); ?>:</b>
	<?php
		$create_user = User::model()->findbyPk($data->religion_created_by);
	?>
	<?php echo CHtml::encode($create_user->user_organization_email_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('religion_created_date')); ?>:</b>
	<?php echo CHtml::encode($data->religion_created_date); ?>
	<br />


</div>

protected/views/religion/admin.php
<?php
$this->breadcrumbs=array(
	'Religions'=>array('admin'),
	'Manage',
);

$this->menu=array(
//	array('label'=>'List Religion', 'url'=>array('index')),
	array('label'=>'', 'url'=>array('create'),'linkOptions'=>array('class'=>'Create','title'=>'Add')),
	
	array('label'=>'', 'url'=>array('ExportToPDFExcel/ReligionExportToPdf'),'linkOptions'=>array('class'=>'export-pdf','title'=>'Export To Pdf','target'=>'_blank')),
	array('label'=>'', 'url'=>array('ExportToPDFExcel/ReligionExportToExcel'),'linkOptions'=>array('class'=>'export-excel','title'=>'Export To Excel','target'=>'_blank')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('religion-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Religions</h1>

<!--<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>-->

<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->
<?php
$dataProvider = $model->search();
if(Yii::app()->user->getState("pageSize",@$_GET["pageSize"]))
$pageSize = Yii::app()->user->getState("pageSize",@$_GET["pageSize"]);
else
$pageSize = Yii::app()->params['pageSize'];
$dataProvider->getPagination()->setPageSize($pageSize);
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'religion-grid',
	'dataProvider'=>$dataProvider,
	'filter'=>$model,
	'columns'=>array(
		array(
		'header'=>'SI No',
		'class'=>'IndexColumn',
		),
		//'religion_id',
		'religion_name',
		//'religion_organization_id',
		//'religion_created_by',
		//'religion_created_date',
		/* 
		array('name'=>'Organization',
			'value'=>'Organization::model()->findByPk($data->religion_organization_id)->organization_name',
			'filter' => false,

		),
		array('name'=>'religion_created_date',
			'value'=>'$data->religion_created_date',
			'filter' => false,

		),*/ 

		array(
			'class'=>'MyCButtonColumn',
		),
	),
'pager'=>array(
		'class'=>'AjaxList',
		//'maxButtonCount'=>25,
		'maxButtonCount'=>$model->count(),
		'header'=>''
	    ),
)); ?>

protected/views/religion/create.php
<?php
$this->breadcrumbs=array(
	'Religions'=>array('admin'),
	'Add',
);

$this->menu=array(
//	array('label'=>'List Religion', 'url'=>array('index')),
	array('label'=>'', 'url'=>array('admin'),'linkOptions'=>array('class'=>'Manage','title'=>'Manage')),
);
?>

<h1>Add Religion</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/religion/index.php
<?php
$this->breadcrumbs=array(
	'Religions',
);

$this->menu=array(
	array('label'=>'', 'url'=>array('create'),'linkOptions'=>array('class'=>'Create','title'=>'Create')),
	array('label'=>'', 'url'=>array('admin'),'linkOptions'=>array('class'=>'Manage','title'=>'Manage')),
);
?>

<h1>Religions</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/religion/update.php
<?php
$this->breadcrumbs=array(
	'Religions'=>array('admin'),
	//$model->religion_name=>array('view','id'=>$model->religion_id),
	$model->religion_name,
	'Edit',
);

$this->menu=array(
//	array('label'=>'List Religion', 'url'=>array('index')),
	array('label'=>'', 'url'=>array('create'),'linkOptions'=>array('class'=>'Create','title'=>'Add')),
	array('label'=>'', 'url'=>array('view', 'id'=>$model->religion_id),'linkOptions'=>array('class'=>'View','title'=>'View')),
	array('label'=>'', 'url'=>array('admin'),'linkOptions'=>array('class'=>'Manage','title'=>'Manage')),
);
?>

<h1>Edit Religion  <?php //echo $model->religion_id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/religion/view.php
<?php
$this->breadcrumbs=array(
	'Religions'=>array('admin'),
	$model->religion_name,
);

$this->menu=array(
//	array('label'=>'List Religion', 'url'=>array('index')),
	array('label'=>'', 'url'=>array('create'),'linkOptions'=>array('class'=>'Create','title'=>'Add')),
	array('label'=>'', 'url'=>array('update', 'id'=>$model->religion_id),'linkOptions'=>array('class'=>'Edit','title'=>'Update')),
	array('label'=>'', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->religion_id),'confirm'=>'Are you sure you want to delete this item?', 'class'=>'Delete','title'=>'Delete')),
	array('label'=>'', 'url'=>array('admin'),'linkOptions'=>array('class'=>'Manage','title'=>'Manage')),
);
?>

<h1>View Religion</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
//		'religion_id',
		'religion_name',
//		'religion_organization_id',
//		'religion_created_by',
		array('name'=>'religion_created_by',
			'value'=>User::model()->findByPk($model->religion_created_by)->user_organization_email_id,
		),

		//'religion_created_date',
		array(
                'name'=>'religion_created_date',
                'type'=>'raw',		
                'value'=>($model->religion_created_date == 0000-00-00) ? 'Not Set' : date_format(new DateTime($model->religion_created_date), 'd-m-Y'),
	        ),
		/*
		array('name'=>'Organization:',
			'value'=>Organization::model()->findByPk($model->religion_organization_id)->organization_name,
			'filter' => false,

		),*/
	),
)); ?>